# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@3.0

jobs:
  build-ebs-mac-xcode:
    parameters:
      xcode_version:
        default: "13.3.0"
        type: string
    macos:
      xcode: <<parameters.xcode_version>>
    environment:
      EBS_VERSION: 3.0.0
      NDI_PLUGIN_RELEASE_TAG: 4.9.1-custom
      NDI_PLUGIN_REPO: https://github.com/evercast/obs-ndi.git
      EBS_DEPS_PATH: /tmp/obs-deps
      EBS_DEPS_QT_PATH: /tmp/obs-deps-qt
      EBS_LIBWEBRTC_PATH: /tmp/libwebrtc/cmake
    steps:
      - checkout
      - run: git submodule sync
      - run: git -c http.sslVerify=false submodule update --init
      - run:
          name: install deps
          command: |
            brew install cmake
            brew install jack
            
            mkdir -p /tmp
            curl -L https://github.com/obsproject/obs-deps/releases/download/2022-02-13/macos-deps-2022-02-13-universal.tar.xz -o /tmp/obs-deps.tar.xz
            curl -L https://github.com/obsproject/obs-deps/releases/download/2022-02-13/macos-deps-qt-2022-02-13-universal.tar.xz -o /tmp/obs-deps-qt.tar.xz
            
            mkdir -p $EBS_DEPS_PATH
            mkdir -p $EBS_DEPS_QT_PATH
            tar -xzf /tmp/obs-deps.tar.xz -C $EBS_DEPS_PATH
            tar -xzf /tmp/obs-deps-qt.tar.xz -C $EBS_DEPS_QT_PATH
          working_directory: deps-install

      - run:
          name: get ndi runtime
          working_directory: /tmp
          command: |
            destFile="ndi-runtime.pkg"
            curl -L https://github.com/evercast/evercast-broadcaster-software/releases/download/3.0.0/ndi-runtime-4.5.1-macOS.pkg -o $destFile
            ls

      - run:
          name: get ndi runtime m1
          working_directory: /tmp
          command: |
            destFile="ndi-runtime-m1.pkg"
            curl -L https://github.com/evercast/evercast-broadcaster-software/releases/download/3.0.0/ndi-runtime-m1.pkg -o $destFile
            ls

      - run:
          name: get libwebrtc
          working_directory: /tmp
          command: |
            destFile="/tmp/libwebrtc"
            filename="libwebrtc.zip"
            curl -L https://github.com/evercast/evercast-broadcaster-software/releases/download/3.0.0/libwebrtc-87.zip -o $filename
            unzip -o ${filename} -d ${destFile}
            ls

      - run:
          name: build_EBS
          working_directory: .
          command: |
            ./CI/before-script-osx.sh
            cd build
            cmake --build . --config RELEASE

      - run:
          name: check built libs
          command: |
            ls ~/project/build/UI/obs-frontend-api/
            ls ~/project/build/libobs/
            ls /tmp/

      - run:
          name: build_NDI_PLUGIN
          working_directory: /tmp
          command: |
            MY_DIR=`eval echo ~$USER`
            echo $MY_DIR
            git clone -b $NDI_PLUGIN_RELEASE_TAG $NDI_PLUGIN_REPO
            cd obs-ndi
            mkdir build
            cd build
            cmake \
                -DLIBOBS_INCLUDE_DIR=$MY_DIR/project/libobs \
                -DLIBOBS_LIB=$MY_DIR/project/build/libobs/libobs.0.dylib \
                -DOBS_FRONTEND_LIB=$MY_DIR/project/build/UI/obs-frontend-api/libobs-frontend-api.dylib \
                -DQt5Core_DIR=$EBS_DEPS_QT_PATH/lib/cmake/Qt5Core \
                -DQt5Widgets_DIR=$EBS_DEPS_QT_PATH/lib/cmake/Qt5Widgets \
                -DQTDIR=$EBS_DEPS_QT_PATH \
                ../
            
            make

      - run:
          name: pack .app
          environment:
            NDI_PATH: /tmp/obs-ndi
            NDI_RUNTIME: /tmp/ndi-runtime.pkg
            NDI_M1_RUNTIME: /tmp/ndi-runtime-m1.pkg
          command: |
            sudo -E ./CI/before-deploy-osx.sh
            cd build/
            sudo -E sh ../CI/install/osx/app2dmg.sh
            mkdir -p artifacts
            cp ./EBS_"$EBS_VERSION"_Install.dmg ./artifacts/EBS_"$EBS_VERSION"_Install.dmg
            cd artifacts/
            ls

      - run:
          name: ckeck .app libs
          command: |
            echo "################################################"
            echo "## LIBS"
            echo " "
            ls ./build/EBS.app/Contents/Frameworks
            echo " "
            echo "################################################"
            echo "################################################"
            echo "## PLUGINS"
            echo " "
            ls ./build/EBS.app/Contents/PlugIns
            echo " "
            echo "################################################"
            

      - store_artifacts:
          path: build/artifacts

  build-ebs-win:
    executor:
      name: win/windows
    environment:
      NDI_PLUGIN_RELEASE_TAG: 4.9.1
      build_config: Release
      EBS_VERSION: 3.0.0
      EBS_VERSION_MAJOR: 3
      EBS_VERSION_MINOR: 0
      EBS_VERSION_PATCH: 0
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: fetch NDI source
          shell: bash.exe
          working_directory: deps-install
          command: |
            git clone -b $NDI_PLUGIN_RELEASE_TAG https://github.com/Palakis/obs-ndi.git
            pwd
            ls

      - restore_cache:
          name: restoring cache
          keys:
            - deps-cache-zips-{{ .Branch }}

      - run:
          name: install deps
          shell: bash.exe
          working_directory: deps-install
          command: |
            choco install cmake -y
            choco install 7zip

            mkdir archives || true
            mkdir ../CI/tools

            echo "#####################################################"
            echo "## DOWNLOADING WIX tools"
            curl -C - -L "https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311-binaries.zip" -o "archives/wix311-binaries.zip"
            echo "## DOWNLOAD COMPLETED"
            7z x "archives/wix311-binaries.zip" -o"../CI/tools"
            echo "## UNZIP COMPLETED"
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING obs-deps"
            curl -C - -L "https://github.com/obsproject/obs-deps/releases/download/win-2022-02-13/windows-deps-2022-02-13.zip" -o "archives/obs-deps.zip"
            echo "## DOWNLOAD COMPLETED"
            7z x "archives/obs-deps.zip" -o"obs-deps"
            echo "## UNZIP COMPLETED"
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING libwebrtc"
            curl -C - -L "https://github.com/evercast/evercast-broadcaster-software/releases/download/3.0.0-win/libwebrtc.7z" -o "archives/libwebrtc.7z"
            echo "## DOWNLOAD COMPLETED"
            7z x "archives/libwebrtc.7z" -o"libwebrtc"
            echo "## UNZIP COMPLETED"
            ls
            echo "##########################"
            ls libwebrtc/
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING ndi runtime"
            curl -C - -L "https://github.com/evercast/evercast-broadcaster-software/releases/download/3.0.0-win/ndi-runtime-5.0-Windows.exe" -o "archives/ndi-runtime-5.0-Windows.exe"
            echo "## DOWNLOAD COMPLETED"
            mv "archives/ndi-runtime-5.0-Windows.exe" .
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING vc_redist.x64.exe"
            curl -C - -L "https://aka.ms/vs/17/release/vc_redist.x64.exe" -o "archives/vc_redist.x64.exe"
            echo "## DOWNLOAD COMPLETED"
            mv archives/vc_redist.x64.exe .
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING Qt_5.15.2.7z"
            curl -C - -L "https://cdn-fastly.obsproject.com/downloads/Qt_5.15.2.7z" -o "archives/Qt_5.15.2.7z"
            7z x archives/Qt_5.15.2.7z -oQt
            echo "## DOWNLOAD COMPLETED"
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING openssl-1.1.tgz"
            curl -C - -L "https://libwebrtc-community-builds.s3.amazonaws.com/openssl-1.1.tgz" -o "archives/openssl-1.1.tgz"
            tar -xzf archives/openssl-1.1.tgz
            echo "## DOWNLOAD COMPLETED"
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING vlc.zip"
            curl -C - -L "https://cdn-fastly.obsproject.com/downloads/vlc.zip" -o "archives/vlc.zip"
            7z x archives/vlc.zip -ovlc
            echo "## DOWNLOAD COMPLETED"
            ls
            echo "##########################"

            echo "#####################################################"
            echo "## DOWNLOADING ffmpeg-5.0.1-full_build.7z"
            curl -C - -L "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.0.1-full_build.7z" -o "archives/ffmpeg.7z"
            7z x archives/ffmpeg.7z -offmpeg
            echo "## DOWNLOAD COMPLETED"
            ls
            echo "##########################"

      - save_cache:
          key: deps-cache-zips-{{ .Branch }}
          name: saving cache
          when: always
          paths:
            - deps-install/archives

      - run:
          name: prepare build folder
          shell: bash.exe
          working_directory: build
          command: |
            cp ../deps-install/vc_redist.x64.exe vc_redist.x64.exe
            cp ../deps-install/ndi-runtime-5.0-Windows.exe ndi-runtime-5.0-Windows.exe
            cp ../CI/install/win/ebs.ico ebs.ico

            echo "## CONTENT:"
            ls

      - run:
          name: check VC
          shell: bash.exe
          command: |
            echo "## 1"
            ls "/c/Program Files (x86)/"
            echo "## 1.1"
            choco install visualstudio2019buildtools
            ls "/c/Program Files (x86)/"
            echo "## 2"
            ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/"
            echo "## 3"
            ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build/"
            echo "## 4"
            pwd


      - run:
          name: check vars
          shell: bash.exe
          command: |

            cd "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build"
            ./vcvars64.bat

            echo "### MSVC versions"
            ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC"
            echo "###"

            ls "/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/"

      - run:
          name: build
          shell: cmd.exe
          working_directory: CI/util
          environment:
            libwebrtcPath: C:/Users/circleci/project/deps-install/libwebrtc/cmake
            opensslPath: C:/Users/circleci/project/deps-install/openssl-1.1/x64
            QTDIR64: C:/Users/circleci/project/deps-install/Qt/5.15.2/msvc2019_64
            ffmpegPath: C:/Users/circleci/project/deps-install/ffmpeg
            DepsPath64: C:/Users/circleci/project/deps-install/obs-deps/win64
            VLCPath: C:/Users/circleci/project/deps-install/vlc
            NDIPath: C:/Users/circleci/project/deps-install/obs-ndi/obs-plugins

          command: |
            .\win_build_ci.cmd

      - run:
          name: build NDI plugin
          shell: cmd.exe
          working_directory: CI\util
          command: .\win_build_ndi.cmd

      - run:
          name: check build dir
          shell: bash.exe
          working_directory: build
          command: |
            ls

      - run:
          name: package
          shell: cmd.exe
          working_directory: build
          command: ..\CI\util\package-installer.cmd

      - store_artifacts:
          path: build\artifacts

workflows:
  build-ebs-mac-workflow:
    jobs:
      - build-ebs-mac-xcode:
          matrix:
            parameters:
              xcode_version:
                - 14.0.0
                - 13.4.1
                - 13.3.0
  build-ebs-win-workflow:
    jobs:
      - build-ebs-win

